CasaDaVideira/Controllers/CategoriaController.cs
using CasaDaVideira.Model.Database;
using CasaDaVideira.Model.Database.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CasaDaVideira.Controllers
{
    using CasaDaVideira.Model.Database.Utils;

    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            var categorias = DbConfig.Instance.CategoriaRepository.FindAll();
            
            return View(categorias);
        }

        public PartialViewResult CreateCategoria()
        {
            if (LoginUtils.Usuario != null && LoginUtils.Usuario.Admin)
                return PartialView("_CadastroCategoria", new Categoria());
            throw new Exception("Tentativa ilegal de acesso - Not Admin user");
        }

        public ActionResult GravarCategoria(Categoria categoria)
        {
            DbConfig.Instance.CategoriaRepository.Save(categoria);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid idCategoria)
        {
            var categoria = DbConfig.Instance.CategoriaRepository.FindFirstById(idCategoria);
            categoria.Ativo = false;
            DbConfig.Instance.CategoriaRepository.Update(categoria);
            return RedirectToAction("Index");
        }
    }
}

CasaDaVideira/Controllers/HomeController.cs
using CasaDaVideira.Model.Database;
using CasaDaVideira.Model.Database.Utils;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CasaDaVideira.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index() => View();

        [AllowAnonymous]
        public PartialViewResult Login()
        {
            if (DbConfig.Instance.UsuarioRepository.SystemHasAdmin())
            {
                return PartialView("_Login", LoginUtils.Usuario);
            }
            else
            {
                return PartialView("_CadastraAdmin");
            }
        }

        
        public PartialViewResult Configuracoes()
        {
            if(LoginUtils.Usuario != null)
            {
                if (LoginUtils.Usuario.Admin)
                {
                    return PartialView("_Configuracoes");
                }
            }
            throw new Exception("Tentativa de fraude!");
        }
    }
}

CasaDaVideira/Controllers/ProdutoController.cs
using CasaDaVideira.Model.Database;
using CasaDaVideira.Model.Database.Model;
using CasaDaVideira.Model.Database.Utils;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CasaDaVideira.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult Index()
        {
            var produtos = DbConfig.Instance.ProdutoRepository.FindAll();
            ViewBag.Categorias = DbConfig.Instance.CategoriaRepository.FindAll();
            var qtdProdutos = DbConfig.Instance.ProdutoRepository.CountProdutos();
            int paginas = qtdProdutos / 9;
            if (qtdProdutos % 9 != 0)
                paginas++;
            ViewBag.QtdPaginas = paginas;
            return View(produtos);
        }    
        public ActionResult Listar()
        {
            var produtos = DbConfig.Instance.ProdutoRepository.FindAll();
            return View(produtos);
        }    
        public PartialViewResult CreateProduto()
        {
            if (LoginUtils.Usuario != null && LoginUtils.Usuario.Admin)
            {
                var categs = DbConfig.Instance.CategoriaRepository.FindAll();

                ViewBag.Categorias = new SelectList(categs, "Id", "Nome");

                return PartialView("_CadastraProduto", new Produto());
            }
                
            throw new Exception("Tentativa ilegal de acesso - Not Admin user");
        }
        public ActionResult UpdateProduto(Produto produto)
        {
            Produto p = DbConfig.Instance.ProdutoRepository.FindFirstById(produto.Id);

            p.Preco = produto.Preco;
            p.Categoria = produto.Categoria;
            p.Classificacao = produto.Classificacao;
            p.DescricaoCompleta = produto.DescricaoCompleta;
            p.Imagens = produto.Imagens;
            p.Nome = produto.Nome;
            p.Oferta = produto.Oferta;
            p.Peso = produto.Peso;

            DbConfig.Instance.ProdutoRepository.Update(p);

            return View("Listar", DbConfig.Instance.ProdutoRepository.FindAll());
        }
        public ActionResult EditProduto(Guid idProduto)
        {
            var prod = DbConfig.Instance.ProdutoRepository.FindAll().FirstOrDefault(f => f.Id == idProduto);

            return View("_EditProduto",prod);
        }
        public PartialViewResult FiltroCategoria(Guid idCategoria)
        {
            var produtos = DbConfig.Instance.ProdutoRepository.FindAllByCategoria(idCategoria);
            ViewBag.Categorias = DbConfig.Instance.CategoriaRepository.FindAll();
            var qtdProdutos = produtos.Count();
            int paginas = qtdProdutos / 9;
            if (qtdProdutos % 9 != 0)
                paginas++;
            ViewBag.QtdPaginas = paginas;
            return PartialView("_ProdutosPaginados", produtos);
        }
        public ActionResult DeleteProduto(Guid idProduto)
        {
            var prod = DbConfig.Instance.ProdutoRepository.FindAll().FirstOrDefault(f => f.Id == idProduto);
            prod.Ativo = false;
            DbConfig.Instance.ProdutoRepository.Update(prod);

            return RedirectToAction("Listar");
        }
        public ActionResult DetailsProduto(Guid idProduto)
        {
            var prod = DbConfig.Instance.ProdutoRepository
                    .FindAll().FirstOrDefault(f => f.Id == idProduto);

            return View(prod);
        }
        public ActionResult GravarProduto(Produto prod, Guid idCategoria)
        {
            prod.Categoria = DbConfig.Instance.CategoriaRepository.FindFirstById(idCategoria);
            
            DbConfig.Instance.ProdutoRepository.Save(prod);
            //return View("Telefones");
            return RedirectToAction("Listar");
        }
        
        public PartialViewResult AddImagem(Guid idProduto)
        {
            Produto produto = DbConfig.Instance.ProdutoRepository.FindFirstById(idProduto);
            return PartialView("AddImagem", produto);
        }    
        public ActionResult InsereImagem(HttpPostedFileBase file, Guid idProduto)
        {
            if (file != null && file.ContentLength > 0)
            {
                var produto = DbConfig.Instance.ProdutoRepository.FindFirstById(idProduto);

                
                // extract only the filename
                var fileName = Path.GetFileName(file.FileName);

                
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/images/uploads/produtos/"), fileName);
                file.SaveAs(path);

                var caminho = "images/uploads/produtos/" + fileName;
                var imagem = new Imagem()
                {
                    DataInclusao = DateTime.Now,
                    Produto = produto,
                    Caminho = caminho                    
                };
                DbConfig.Instance.ImagemRepository.Save(imagem);
                produto.Imagens.Add(imagem);
                DbConfig.Instance.ProdutoRepository.Update(produto);
            }
            // redirect back to the index action to show the form once again
            return RedirectToAction("Index");
        }

        public ActionResult RateProduto(int rating, Guid idProduto)
        {            
            var produto = DbConfig.Instance.ProdutoRepository.FindFirstById(idProduto);
            
            produto.Classificacao += rating;                                    
            produto.QtdRating++;

            DbConfig.Instance.ProdutoRepository.Update(produto);
            return View("DetalheProduto", produto);
        }
        public ActionResult Comprar(object obj)
        {
            return RedirectToAction("Index");
        }
        public ActionResult BuscarProduto(string search)
        {
            var user = LoginUtils.Usuario;
            var br = new BuscaRealizada();
            br.Busca = search;
            br.Usuario = user;
            user.BuscasRealizadas.Add(br);
            DbConfig.Instance.UsuarioRepository.Update(user);            
            
            
            var prods = DbConfig.Instance.ProdutoRepository.FindByName(search);
            ViewBag.Categorias = DbConfig.Instance.CategoriaRepository.FindAll();
            var qtdProdutos = DbConfig.Instance.ProdutoRepository.CountProdutos();
            int paginas = qtdProdutos / 9;
            if (qtdProdutos % 9 != 0)
                paginas++;
            ViewBag.QtdPaginas = paginas;
            if (prods.Count() > 0)
                return View("Index", prods);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult DetalheProduto(Guid idProduto)
        {
            var produto = DbConfig.Instance.ProdutoRepository.FindFirstById(idProduto);
            return View(produto);
        }        

        public PartialViewResult AddProdutoToCart(Guid idProduto)
        {
            //var carrinho = DbConfig.Instance.CarrinhoRepository.FindFirstById(idCarrinho);
            var produto = DbConfig.Instance.ProdutoRepository.FindFirstById(idProduto);
            if(produto.Qtd > 0)
            {
              //  carrinho.Produtos.Add(produto);
                produto.Qtd--;
                DbConfig.Instance.ProdutoRepository.Update(produto);
            }
            //DbConfig.Instance.CarrinhoRepository.Update(carrinho);
            return PartialView("_ProdutosPaginados", DbConfig.Instance.ProdutoRepository.FindAll());
        }
    }
}

CasaDaVideira/Views/Home/_CadastraAdmin.cshtml
@model CasaDaVideira.Model.Database.Model.Usuario
@using System.ComponentModel.DataAnnotations
@using CasaDaVideira.Model.Database.Utils

<div id="modalLogin" role="dialog" class="login modal fade">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modalLogin">&times;</button>
            <div class="modal-body">
                <h2>Cadastro Administrador</h2>

                <div class="alert alert-danger" role="alert">
                    Insira as credenciais para cadastrar o primeiro administrador!<br />
                    Não será possível logar nenhum usuário sem um administrador cadastrado.
                </div>

                <div id="validateTk" class="login-form-grids animated wow slideInUp" data-wow-delay=".5s">
                    @using (Ajax.BeginForm("CadastraAdmin", "Usuario", new AjaxOptions()
                    {
                        HttpMethod = "post",
                        OnSuccess = "cadastroSucesso",
                        OnFailure = "falhaCadastroUsuario",
                        LoadingElementId = "loadAjax",
                        InsertionMode = InsertionMode.InsertAfter,
                        UpdateTargetId = "modaldiv"
                    }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Chave do sistema" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                        @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @placeholder = "Senha", @type = "password" } })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        
                        <input id="btnCadastroPrimeiroAdmin" type="submit" value="Cadastrar primeiro administrador">
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CasaDaVideira/Views/Home/_Configuracoes.cshtml
@using CasaDaVideira.Model.Database.Utils
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Configurações";
    var usuario = LoginUtils.Usuario;
}
@if (usuario != null && usuario.Admin)
{
    <div class="container">
        <div class="row" style="margin: 50px">
            <div class="col-md-4">
                <h4>Produtos</h4>
                <hr />
                <ul class="list-unstyled input-group">
                    <li>
                        @Ajax.ActionLink("Cadastrar Produto", "CreateProduto", "Produto", new AjaxOptions()
             {
                 HttpMethod = "post",
                 OnSuccess = "showCadastroProduto",
                 OnFailure = "failCadastroProduto",
                 LoadingElementId = "loadAjax",
                 InsertionMode = InsertionMode.Replace,
                 UpdateTargetId = "modaldiv"
             })
                    </li>
                    <li>
                        @Ajax.ActionLink("Cadastrar Categoria", "CreateCategoria", "Categoria", new AjaxOptions()
                     {
                         HttpMethod = "post",
                         OnSuccess = "showCadastroCategoria",
                         OnFailure = "fail(data)",
                         LoadingElementId = "loadAjax",
                         InsertionMode = InsertionMode.Replace,
                         UpdateTargetId = "modaldiv"
                     })
                    </li>
                    <li>
                        @Html.ActionLink("Listar Produtos", "Listar", "Produto")
                    </li>
                    <li>
                        @Html.ActionLink("Listar Categorias", "Index", "Categoria")
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Clientes</h4>
                <hr />
                <ul class="list-unstyled input-group">
                    <li>
                        @Html.ActionLink("Listar Clientes", "ListarClientes", "Usuario")
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Usuários</h4>
                <hr />
                <ul class="list-unstyled input-group">
                    <li>
                        @Html.ActionLink("Listar Administradores", "Index", "Usuario")
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

CasaDaVideira/Views/Home/_Login.cshtml
@model CasaDaVideira.Model.Database.Model.Usuario
@using System.ComponentModel.DataAnnotations
@using CasaDaVideira.Model.Database.Utils

@{
    var usuario = LoginUtils.Usuario;
    ViewBag.Title = "Login";
}

<div id="modalLogin" role="dialog" class="login modal fade">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modalLogin">&times;</button>
            <div class="modal-body">
                <h2>Login</h2>

                <div class="login-form-grids animated wow slideInUp" data-wow-delay=".5s">
                    @using (Ajax.BeginForm("FazerLogin", "Usuario", new AjaxOptions()
                    {
                        HttpMethod = "post",
                        OnSuccess = "loginSucesso",
                        OnFailure = "falhaLogin",
                        LoadingElementId = "loadAjax",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "loginMenu"
                    }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                        @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @placeholder = "Senha", @type = "password" } })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })

                        <div class="forgot">
                            <a href="#">Esqueceu sua senha?</a>
                        </div>
                                                
                        <input type="submit" value="Entrar">
                    }
                </div>
                <h4>Não tem login?</h4>
                <p>
                    @Html.ActionLink("Crie seu cadastro!", "CreateUser", "Usuario") Ou volte para
                    @Html.ActionLink("página inicial", "Index", "Home")
                </p>
            </div>
        </div>
    </div>
</div>